server:
  port: 8080
  servlet:
    context-path: /bigdatapf
spring:
  datasource:
    name: bigdatapf_DS
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置

    #监控统计拦截的filters
    filters: stat
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性
    url: jdbc:mysql://192.168.43.111:3306/spark_project?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: hive
    password: hive
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多长时间进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache,并指定每个连接上PSCache的大小。oracle设为true,mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

#配置mybatis框架
mybatis:
  #定义Mapper接口映射文件位置
  mapper-locations: classpath:mapper/*.xml
  #定义实体类位置
  type-aliases-package: com.behavioranalysis.pojo
#控制台打印sql语句
logging:
  level:
    com.behavioranalysis.mapper: debug

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


